name: Generate Snake Animation

on:
  # Ejecutar autom치ticamente cada 24 horas
  schedule:
    - cron: "0 */24 * * *"
  
  # Permitir ejecuci칩n manual
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Clonar el repositorio
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generar la animaci칩n de la gr치fica de contribuciones general
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      # Publicar los archivos generados en un branch
      - name: Publish Snake Animation
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
